### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by KalinaMatysiak** [Cammisuli/monodon#20]
### Current Behavior
I wanted to customize the generator. My customized generator works perfectly, but when I would like to run tests, get the error:  `ReferenceError: TextDecoder is not defined`

### GitHub Repo
https://github.com/KalinaMatysiak/bug-reproduction-monodon-rust

### Steps to Reproduce
 - Clone the Repo
 - Run `pnpm install`
 - Run `pnpm nx test my-plugin`

### Failure Logs

```
packages/my-plugin/src/generators/rust-app/generator.spec.ts
  ● Test suite failed to run

    ReferenceError: TextDecoder is not defined

      2 | import type { Tree } from '@nx/devkit';
      3 |
    > 4 | import generator from '@monodon/rust/src/generators/binary/generator';
        | ^
      5 | import { formatFiles, generateFiles } from '@nx/devkit';
      6 |
      7 | import * as path from 'path';

      at ../../node_modules/.pnpm/@ltd+j-toml@1.38.0/node_modules/@ltd/j-toml/index.js:1138:23
      at ../../node_modules/.pnpm/@ltd+j-toml@1.38.0/node_modules/@ltd/j-toml/index.js:2:81
      at Object.<anonymous> (../../node_modules/.pnpm/@ltd+j-toml@1.38.0/node_modules/@ltd/j-toml/index.js:5:3)
      at Object.<anonymous> (../../node_modules/.pnpm/@monodon+rust@1.1.2_q5uzlubyxbop7sm5usegwh6nuq/packages/rust/src/utils/toml.ts:1:1)
      at Object.<anonymous> (../../node_modules/.pnpm/@monodon+rust@1.1.2_q5uzlubyxbop7sm5usegwh6nuq/packages/rust/src/utils/add-to-workspace.ts:2:1)
      at Object.<anonymous> (../../node_modules/.pnpm/@monodon+rust@1.1.2_q5uzlubyxbop7sm5usegwh6nuq/packages/rust/src/generators/binary/generator.ts:16:1)
```

### Operating system:
 - Linux

**Comment by Cammisuli** [comment]
hmm interesting.. I see it in the repro repo. I'll try and investigate whats happening. But at a quick glance, it looks like its coming from the toml library that I use. 

I'll take a closer look soon. Thanks for the report!

**Comment by Cammisuli** [comment]
So it looks like your jest config wasn't using the node environment. So add `testEnvironment: 'node'` to `packages/my-plugin/jest.config.ts`, and the `TextDecoding` issue should go away. 

![image](https://github.com/Cammisuli/monodon/assets/4332460/97cf2312-95be-45d9-8117-e813f77d3260)
