### ISSUE TITLE
Errors when using dependencies from github

### ISSUE THREAD

**Issue by maxmousse** [Cammisuli/monodon#40]
Hi everyone,

After adding a dependencie from github to my project, I have the next error when executing targets any targets in the project:

```
 >  NX   Failed to process project dependencies with "@monodon/rust".

   Source file "/home/maxim/.cargo/git/checkouts/prisma-engines-8e1416dd0e571d11/c4aeef8/psl/builtin-connectors/Cargo.toml" does not exist in the workspace.
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

I am using nx@17.2.8, and here is the dependencie that causes problems:

```
[package]
name = "prisma-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11", default-features = false, features = [ "postgresql"] }
```

From what I understand, it happens because the plugin reads the Cargo file of the github dependencie, which is outside of the monorepo.

The cargo files are tracked as inputs for the nx cache, am I right ? Is there a way to ignore the cargo files of these kind of dependencies without messing with the cache too much ?

Tell me if there is anything I can do help =)

**Comment by ewized** [comment]
Once you make this change in this pr https://github.com/Cammisuli/monodon/pull/37 you can use git repos

**Comment by maxmousse** [comment]
Oh cool if #37 solves this! Once again, tell me if any help is needed, I'd be happy to contribute
