### ISSUE TITLE
Support @napi-rs/cli 3.0 

### ISSUE THREAD

**Issue by Brooooooklyn** [Cammisuli/monodon#48]
`@napi-rs/cli` 3.0 has some breaking changes, the build flags changed: https://github.com/napi-rs/napi-rs/blob/main/cli/docs/build.md

I haven't had time to write the migration guide yet, I will post it here once I'm done.

@napi-rs/cli 3.0 also supports the new wasm targets, and there are a series of new cli-generated artifacts files, which also need to be supported.

**Comment by Cammisuli** [comment]
Awesome, thanks! I'll see if I can figure it out while we wait for the guide.
